create table hotel (
    id integer not null generated by default as identity (start with 10),
    nome varchar(50),
    telefono varchar(20),
    provincia char(2),
    primary key (id)
);
create table stanza (
    id integer not null generated by default as identity (start with 10),
    nome varchar(255),
    prezzo float(53) not null,
    hotel_id integer references hotel(id) on delete cascade on update cascade,
    primary key (id)
);